on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: CI

jobs:
  ci-linux:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable]

        include:
          # Test nightly but don't fail
          - rust: nightly
            experimental: true
            TARGET: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.TARGET }}

      - name: Install libusb library
        run: sudo apt-get install -y libusb-1.0.0-dev

      - run: cargo check --all-targets
      - run: cargo check --features control-buffer-256
      - run: cargo check --features defmt
