on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: Code formatting check

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features
      - run: cargo clippy --features defmt
      - run: cargo clippy --features control-buffer-256
      - run: cargo clippy
